- name: Update apt-cache 
  become: true # notes from https://stackoverflow.com/questions/41535838/how-to-run-apt-update-and-upgrade-via-ansible-shell
  apt: 
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400 #one day

- name: be sure vim is installed
  become: true
  apt: name="{{'vim'}}" state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops

- name: Set up repo
  become: true
  apt: name={{item}} state=latest install_recommends=no 
  with_items:
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: identify docker engine repo
  shell: "curl -sS https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: attach repo
  shell: 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list'

- name: Update apt-cache
  become: true
  apt:
    update_cache: yes

- name: Set up repo
  become: true
  apt: name={{item}} state=latest install_recommends=no 
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
